### PR TITLE
Feature: 404 page

### PR DESCRIPTION
**Pull request by So1ene**
# 404 page: #

**A styled 404 page to replace this empty 404 page:
image

- Test URL: https://404-page--stock--wbstry.hlx.page/pages/404.html

- It selects a random video each time you refresh the page.

- XD Specs: [(A)](https://xd.adobe.com/view/ec215ff3-c052-41cc-837e-70c5fcccd815-b972/specs/), [(B)](https://xd.adobe.com/view/ec215ff3-c052-41cc-837e-70c5fcccd815-b972/screen/5add115c-1712-4594-ab65-20514116566b/specs/), [(C)](https://xd.adobe.com/view/ec215ff3-c052-41cc-837e-70c5fcccd815-b972/screen/125cb23c-394f-407e-8bdf-20c78f9e797e/specs/)

### CODE REVIEW

**Review by auniverseaway — CHANGES_REQUESTED** [review]
Use milo-college as your sample for how to do 404s correctly.

**Comment by auniverseaway** [comment]
@So1ene fix the conflicts and we can merge this.

**Comment by So1ene** [comment]
@auniverseaway the conflicts were fixed!

**Comment by rgclayton** [comment]
Closing per @williambsm request.

**Pull request closed without merging**
